// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzktwerypqoisbdoxmap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6a3R3ZXJ5cHFvaXNiZG94bWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODgxNDksImV4cCI6MjA1Nzk2NDE0OX0.7sUZdsGO8eYf3M6DVNX41QPGiluq5cJxA5LxNXDCY80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);